name: dls
description: Linux's "ls" utility written in Dart.
version: 1.0.0
homepage: https://github.com/iamtheblackunicorn/dls
environment:
  sdk: '>=2.12.0 <3.0.0'
dev_dependencies:
  pedantic: ^1.9.0
